export enum EspecialidadeMedico {
    PNEUMOLOGIA = 'PNEUMOLOGIA',
    ALERGOLOGIA = 'ALERGOLOGIA',
    IMUNOALERGOLOGIA = 'IMUNOALERGOLOGIA',
    MEDICINA_INTERNA = 'MEDICINA INTERNA',
    MEDICINA_GERAL_FAMILIAR = 'MEDICINA GERAL E FAMILIAR',
    OTORRINOLARINGOLOGIA = 'OTORRINOLARINGOLOGIA',
    PEDIATRIA = 'PEDIATRIA',
    CIRURGIA_TORACICA = 'CIRURGIA TORÁCICA',
}
