export enum Tabagismo {
    NAO_FUMADOR = 'NÃO FUMADOR',
    EX_FUMADOR = 'EX-FUMADOR',
    EXPOSICAO_PASSIVA = 'EXPOSIÇÃO PASSIVA',
    OCASIONAL = 'OCASIONAL',
    MENOS_10_CIGARROS_DIA = 'MENOS DE 10 CIGARROS/DIA',
    _10_A_20_CIGARROS_DIA = '10 A 20 CIGARROS/DIA',
    MAIS_20_CIGARROS_DIA = 'MAIS DE 20 CIGARROS/DIA'
}