export enum TipoExame {
    // Função respiratória
    ESPIROMETRIA = 'ESPIROMETRIA',
    PICO_FLUXO = 'PICO FLUXO',
    PLETISMOGRAFIA = 'PLETISMOGRAFIA',
    PRESSOES_RESPIRATORIAS = 'PRESSOES RESPIRATORIAS MAXIMAS',
    TESTE_BRONCODILATADOR = 'TESTE BRONCODILATADOR',
    TESTE_BRONCOPROVOCACAO = 'TESTE BRONCOPROVOCACAO',
    TESTE_ESFORCO = 'TESTE DE ESFORCO',
    OXIMETRIA_PULSO = 'OXIMETRIA DE PULSO',
    OXIMETRIA_NOTURNA = 'OXIMETRIA NOTURNA',
    GASOMETRIA_ARTERIAL = 'GASOMETRIA ARTERIAL',
    // Imagiologia
    RADIOGRAFIA_TORACICA = 'RADIOGRAFIA TORACICA',
    TAC_TORACICA = 'TAC TORACICA',
    ECOGRAFIA_TORACICA = 'ECOGRAFIA TORACICA',
    // Procedimentos invasivos
    BRONCOSCOPIA = 'BRONCOSCOPIA',
    LAVAGEM_BRONCOALVEOLAR = 'LAVAGEM BRONCOALVEOLAR',
    BIOPSIA_BRONQUICA = 'BIOPSIA BRONQUICA',
    // Alergia / Imunologia
    INTRADERMORREACAO = 'INTRADERMORREACAO',
    TESTE_PROVOCACAO_ORAL = 'TESTE DE PROVOCACAO ORAL',
    TESTE_PROVOCACAO_NASAL = 'TESTE DE PROVOCACAO NASAL',
    TESTE_PROVOCACAO_BRONQUICA = 'TESTE DE PROVOCACAO BRONQUICA COM ALERGENO',
    IGE_SERICA = 'IGE SERICA',
    IGE_ESPECIFICA = 'IGE ESPECIFICA',
    TRIPTASE_SERICA = 'TRIPTASE SERICA',
    HISTAMINA_SERICA = 'HISTAMINA SERICA',
    // Análises laboratoriais
    HEMOGRAMA = 'HEMOGRAMA',
    ANALISES_SANGUE = 'ANALISES DE SANGUE',
    // ORL / Nasal
    CITOLOGIA_NASAL = 'CITOLOGIA NASAL',
    RINOSCOPIA = 'RINOSCOPIA',
    NASOFIBROSCOPIA = 'NASOFIBROSCOPIA',
    AUDIOGRAMA = 'AUDIOGRAMA',
}
